### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by narayanlongani** [placeforyiming/IROS21-FIDNet-SemanticKITTI#11]
Please share the "evaluate_semantics.py"

As the file is not available in the repository.

**Comment by placeforyiming** [comment]
> Please share the "evaluate_semantics.py"
> 
> As the file is not available in the repository.

that file is part of the semantic kitti api, you can just download it and move the file according to the bash

**Comment by narayanlongani** [comment]
Thanks you
