### ISSUE TITLE
Maybe there is a mistake here.

### ISSUE THREAD

**Issue by huixiancheng** [placeforyiming/IROS21-FIDNet-SemanticKITTI#2]
https://github.com/placeforyiming/IROS21-FIDNet-SemanticKITTI/blob/f48fc021fec10e5f8a0dd194856d161da5a0469a/network/ResNet.py#L469-L487

**Comment by huixiancheng** [comment]
Moreover, what's the meaning of with_normal? Looks like it introduced additional information. Will this effect the result? It looks like the ablation results were not explained and shown in detail in the original paper due to page limitations

**Comment by placeforyiming** [comment]
> Moreover, what's the meaning of with_normal? Looks like it introduced additional information. Will this effect the result? It looks like the ablation results were not explained and shown in detail in the original paper due to page limitations

I just found adding the normal vector can make the training stable. Yes, the paper is a rough one, with some clumsy network modules. So I just keep modifying the structure, to get the current one with simple and naive structure but keeps good performance.

The normal is not extra information, it is calculated from x-y-z, can be considered as a kind of preprocessing step.

How to calculate normal is from:
Fast and accurate computation of surface normals from range images

This paper also gives some explains:
A surface geometry model for lidar depth completion

**Comment by placeforyiming** [comment]
> https://github.com/placeforyiming/IROS21-FIDNet-SemanticKITTI/blob/f48fc021fec10e5f8a0dd194856d161da5a0469a/network/ResNet.py#L469-L487

BTW, which part is the mistake you think? I didn't get it

**Comment by huixiancheng** [comment]
Maybe the 1st condition in 3rd and 4st **if** should be self.if_remission not self.if_range？ 
Thanks for your quick reply.

**Comment by placeforyiming** [comment]
> Maybe the 1st condition in 3rd and 4st **if** should be self.if_remission not self.if_range？
> Thanks for your quick reply.

You are actually right, sorry for the previous confusing answer.

Thanks for pointing it out! I will update the code accordingly

**Comment by placeforyiming** [comment]
> Maybe the 1st condition in 3rd and 4st **if** should be self.if_remission not self.if_range？
> Thanks for your quick reply.

Done, thank you!

**Comment by huixiancheng** [comment]
Thanks for the quick reply and great work again.
