### ISSUE TITLE
How to extend this for instance segmentation ? 

### ISSUE THREAD

**Issue by jediofgever** [placeforyiming/IROS21-FIDNet-SemanticKITTI#7]
Hi, 

I was wondering what needs be done to make the network predicts instance segments instead of semantic ?

**Comment by placeforyiming** [comment]
> Hi,
> 
> I was wondering what needs be done to make the network predicts instance segments instead of semantic ?

This code is about semantic segmentation, if you are interested in instance further, please take a look at our other papers and codebase:

https://github.com/placeforyiming/ICCVW21-LiDAR-Panoptic-Segmentation-TradiCV-Survey-of-Point-Cloud-Cluster

https://github.com/placeforyiming/Divide-and-Merge-LiDAR-Panoptic-Cluster

**Comment by placeforyiming** [comment]
Please feel free to open it again
