### ISSUE TITLE
Visualization Scripts

### ISSUE THREAD

**Issue by ldkong1205** [placeforyiming/IROS21-FIDNet-SemanticKITTI#8]
Thanks for the great work!

Could you provide the visualization code for the demo images in your repository? They look very neat. Thanks
<img width="639" alt="WX20220224-195412@2x" src="https://user-images.githubusercontent.com/44147391/155519197-3c92fb50-72cc-4f5c-b95f-7289a855744b.png">

**Comment by placeforyiming** [comment]
> Thanks for the great work!
> 
> Could you provide the visualization code for the demo images in your repository? They look very neat. Thanks <img alt="WX20220224-195412@2x" width="639" src="https://user-images.githubusercontent.com/44147391/155519197-3c92fb50-72cc-4f5c-b95f-7289a855744b.png">

Hi, I was using  open3d for the visualization, I just simply convert the data format to the compatible version

**Comment by ldkong1205** [comment]
> > Thanks for the great work!
> > Could you provide the visualization code for the demo images in your repository? They look very neat. Thanks <img alt="WX20220224-195412@2x" width="639" src="https://user-images.githubusercontent.com/44147391/155519197-3c92fb50-72cc-4f5c-b95f-7289a855744b.png">
> 
> Hi, I was using open3d for the visualization, I just simply convert the data format to the compatible version

Thank you!
