### ISSUE TITLE
Dear author, where is the evaluate_semantics.py? thanks

### ISSUE THREAD

**Issue by emilyemliyM** [placeforyiming/IROS21-FIDNet-SemanticKITTI#9]
evaluate_semantics.py

I want to run the evaluate_semantics.py, but I can not find it

**Comment by placeforyiming** [comment]
> evaluate_semantics.py
> 
> I want to run the evaluate_semantics.py, but I can not find it

I have a python script to generate the predicted labels, the exact evaluation scripts are provided by the semanticKITTI challenge host.
